version: '3.8'

services:
  rk35xx-builder:
    build: .
    image: rk35xx-builder-image
    container_name: rk35xx_build_env
    command: /bin/bash
    stdin_open: true
    tty: true
    # 网络模式
    network_mode: host
    # 挂载卷
    volumes:
      # 将上一级整个目录挂载到容器的 /workspace
      - ..:/workspace
    # 设置工作目录，进入容器后会自动切换到这个目录
    working_dir: /workspace